### ISSUE TITLE
Server Error: Unknown directive \"defer\

### ISSUE THREAD

**Issue by bogdanned** [apollographql/defer-demo#1]
I am trying to run the server in the example(the simple apollo server one). After running `npm i` and then `npm run start` .

The defer queries fail with the following:

```
"GraphQLError: Unknown directive \"defer\".",
````

Apparently the directive is not recognized by the Apollo server.

**Comment by clarencenpy** [comment]
Fixed with a version bump: https://github.com/apollographql/defer-demo/commit/2a95626dbe88592eb92301efc66d9a901af340c1

**Comment by bogdanned** [comment]
Cloned a fresh copy. Installed the dependencies. Still no @defer directive. I also tried updating `graphql` to latest(^14.0.0). The issues persist. I am testing with the following query:

```
query {
  newsFeed{
    stories{
      text @defer
    }
  }
}

```

**Comment by clarencenpy** [comment]
Could you verify in your package-lock.json that you have `2.1.0-alpha.10` for `apollo-server-core`?

**Comment by bogdanned** [comment]
Just verified that. The version was `2.1.0` but no alpha. I installed alpha manually and now the right version appears in the package-lock.json. The @defer directive is now recognized but the response to the above query is:
```
{
  "error": "Unexpected number in JSON at position 3"
}
```

**Comment by bogdanned** [comment]
That is right. The client works now. Thanks a lot.
